on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Installing dependencies
        run: poetry install --no-interaction
      - name: Build & publish package
        run: poetry publish -b -u $PYPI_USER -p $PYPI_PASSWORD
