name: Create pre-release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Installing dependencies
        run: poetry install --no-interaction
      - name: Build package
        run: poetry build -f wheel
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_TAG }}"
          prerelease: true
          files: |
            ./dist/*.whl
